#!/usr/bin/env bash

# To use the RiverCrossing executable generated by (WSL/Linux)/Android/FreeBSD/MacOS,
# the server needs to be compiled and launched from the same OS.

if [[ `uname -o | grep -E "Msys|Cygwin"` ]]; then
	>&2 echo "MinGW and Cygwin should use 'startWebServer.bat' instead of 'startWebServer.sh'!"
	exit 1
fi

serverPath="./GoServer/cmd/RiverCrossingServer/RiverCrossingServer"
serverSrcPath="./GoServer/cmd/RiverCrossingServer/main.go"

# If the server doesn't exist or is older than the source, (re)build it
buildRequired="false"

if [ ! -x "$serverPath" ]; then
	echo "The non-Windows version of the server was not found or has no 'x' rights. Building it now ..."
	buildRequired="true"

elif [ "$serverSrcPath" -nt "$serverPath" ]; then
	echo "The non-Windows version of the server is older than its source. Rebuilding it ..."
	buildRequired="true"
fi

if [ "$buildRequired" == "true" ]; then
	go build -C ./GoServer/cmd/RiverCrossingServer/ -buildvcs=false \
		|| (>&2 echo "Couldn't build the non-Windows version of the server!"; exit 1)
fi

# Launch the server
"$serverPath"
