/******************************************************************************
 This RiverCrossing project (https://github.com/FlorinTulba/RiverCrossing)
 allows describing and solving River Crossing puzzles:
  https://en.wikipedia.org/wiki/River_crossing_puzzle

 Required libraries:
 - Boost (>=1.83) - https://www.boost.org
 - Microsoft GSL (>=4.0) - https://github.com/microsoft/GSL

 (c) 2018-2026 Florin Tulba (florintulba@yahoo.com)
 *****************************************************************************/

#ifndef H_WARNINGS
#define H_WARNINGS

/*
Warning suppression macros, defined based on the compiler type later:

MUTE_EXPLICIT_NEW_DELETE_WARN warns about using explicit new and delete
operators, which can lead to issues with memory management and object lifetime.

MUTE_GLOBAL_CTOR_WARN warns about global objects that have non-trivial
constructors, which can lead to issues with initialization order.

MUTE_EXIT_TIME_DTOR_WARN warns about static objects with non-trivial destructors
that are destroyed at program exit, which can lead to issues if they depend on
the order of destruction.

MUTE_UNSAFE_BUFF_USE_WARN warns about potential unsafe  buffer usage, such as
when using certain standard library functions that may lead to buffer overflows.
*/

// UNMUTE_WARNING restores the previous warning state after suppression.

// Handle the warning suppression by compiler type
#ifdef __clang__  // Clang (LLVM / Apple Clang / ClangCL)
#define MUTE_EXPLICIT_NEW_DELETE_WARN _Pragma("clang diagnostic push")

#define MUTE_GLOBAL_CTOR_WARN      \
  _Pragma("clang diagnostic push") \
      _Pragma("clang diagnostic ignored \"-Wglobal-constructors\"")

#define MUTE_EXIT_TIME_DTOR_WARN   \
  _Pragma("clang diagnostic push") \
      _Pragma("clang diagnostic ignored \"-Wexit-time-destructors\"")

#define MUTE_UNSAFE_BUFF_USE_WARN           \
  _Pragma("clang diagnostic push") _Pragma( \
      "clang diagnostic ignored \"-Wunsafe-buffer-usage-in-libc-call\"")

#define UNMUTE_WARNING _Pragma("clang diagnostic pop")

#elif defined(__GNUC__) || defined(__GNUG__)  // GCC
#define MUTE_EXPLICIT_NEW_DELETE_WARN _Pragma("GCC diagnostic push")

#define MUTE_GLOBAL_CTOR_WARN _Pragma("GCC diagnostic push")

#define MUTE_EXIT_TIME_DTOR_WARN _Pragma("GCC diagnostic push")

#define MUTE_UNSAFE_BUFF_USE_WARN _Pragma("GCC diagnostic push")

#define UNMUTE_WARNING _Pragma("GCC diagnostic pop")

#elif defined(_MSC_VER)  // MSVC

/// When a constructor is private and not a friend of make_unique / make_shared,
/// new & delete are ok
#define WARN_MSVC_EXPLICIT_NEW_DELETE 26409

#define MUTE_EXPLICIT_NEW_DELETE_WARN \
  __pragma(warning(push))             \
      __pragma(warning(disable : WARN_MSVC_EXPLICIT_NEW_DELETE))

/// Silence global constructors warnings generated by Boost Test macros
#define WARN_MSVC_GLOBAL_CTOR 26426
#define WARN_MSVC_UNNAMED_OBJ 26444

#define MUTE_GLOBAL_CTOR_WARN \
  __pragma(warning(push))     \
      __pragma(warning(disable : WARN_MSVC_GLOBAL_CTOR WARN_MSVC_UNNAMED_OBJ))

#define MUTE_EXIT_TIME_DTOR_WARN __pragma(warning(push))

#define MUTE_UNSAFE_BUFF_USE_WARN __pragma(warning(push))

#define UNMUTE_WARNING __pragma(warning(pop))

#else  // Other compilers
#define MUTE_EXPLICIT_NEW_DELETE_WARN
#define MUTE_GLOBAL_CTOR_WARN
#define MUTE_EXIT_TIME_DTOR_WARN
#define MUTE_UNSAFE_BUFF_USE_WARN

#define UNMUTE_WARNING

#endif  // compiler types

#endif  // !H_WARNINGS
